services:
  postgis:
    build:
      context: ./data
    container_name: strek-db
    shm_size: '256mb'
    environment:
      POSTGRES_DB: strek
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./data:/data
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: safetrek-api
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: safetrek-web
    ports:
      - "81:80"
    depends_on:
      - backend

volumes:
  pgdata:
